openapi: 3.0.0
info:
  title: Reviev platform - OpenAPI 1.0
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/platform
tags:
  - name: User
    description: User API
  - name: Company
    description: Company API
  - name: Review
    description: Review API
  - name: Interview
    description: Interview API

paths:
  /v1/user:
    post:
      operationId: createUser
      summary: Create new user
      tags:
        - User
      requestBody:
        description: Short user DTO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShortUserDto'
        required: true
      responses:
        '201':
          description: created user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
        '400':
          description: Invalid request
        '404':
          description: Resource not found
        '405':
          description: Method is not available
        '500':
          description: Server error

# --- Dtos ---
components:
  schemas:
    # --- User ---
    UserDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: User id
        firstName:
          type: string
          description: User first name
        lastName:
          type: string
          description: User last name
        email:
          type: string
          description: User email

    ShortUserDto:
      type: object
      properties:
        firstName:
          type: string
          description: User first name
        lastName:
          type: string
          description: User last name
        email:
          type: string
          description: User email

    PaginationDto:
      type: object
      properties:
        page:
          type: integer
          description: Number page
        size:
          type: integer
          description: Size all pages
