scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['back-end:8080']
      # host.docker.internal:8080 - запуск на локальной машине на WIN
      # 192.168.0.150:8080 - Дима выделил для App сервера